// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DealerDataContext))]
    partial class DealerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.DealerContact", b =>
                {
                    b.Property<int>("DealerContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DealerInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("PhoneNumberStr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DealerContactId");

                    b.HasIndex("DealerInfoId");

                    b.ToTable("DealerContacts");
                });

            modelBuilder.Entity("API.Models.DealerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DealerInfos");
                });

            modelBuilder.Entity("API.Models.DealerOperatingHour", b =>
                {
                    b.Property<int>("DealerOperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfTheWeek")
                        .HasColumnType("int");

                    b.Property<int?>("DealerInfoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("DealerOperatingHourId");

                    b.HasIndex("DealerInfoId");

                    b.ToTable("DealerOperatingHours");
                });

            modelBuilder.Entity("API.Models.DealerContact", b =>
                {
                    b.HasOne("API.Models.DealerInfo", "DealerInfo")
                        .WithMany("DealerContacts")
                        .HasForeignKey("DealerInfoId");
                });

            modelBuilder.Entity("API.Models.DealerOperatingHour", b =>
                {
                    b.HasOne("API.Models.DealerInfo", "DealerInfo")
                        .WithMany("DealerOperatingHours")
                        .HasForeignKey("DealerInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
